baseURL = 'http://www.discipuladocgv.org/'
languageCode = 'es'
title = 'CGV'
theme = "hugo-universal-theme"
#themesDir = "/"
PublishDir = "docs"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
ShowBreadCrumbs = "true"
# Enable comments by entering your Disqus shortname
disqusShortname = "cgv"
#disqusShortname = "x"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

[markup.goldmark.renderer]
 unsafe = true
 
pluralizelisttitles = false
enableInlineShortcodes = true

[outputs]
  home = ["HTML", "JSON"]
  
[menu]

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

[[menu.main]]
    name = "CGV"
    identifier = "cgv"
    url = "/nosotros/"
    weight = 2

[[menu.main]]
    name = "¿Qué es CGV?"
    url = "/nosotros/somos-diferentes/"
    parent = "cgv"
    weight = 1

[[menu.main]]
    name = "Nuestra Visión"
    url = "/nosotros/"
    parent = "cgv"
    weight = 2

[[menu.main]]
    name = "Currículo"
    identifier = "curriculo"
    url = "/curriculo/"
    weight = 3

[[menu.main]]
    name = "Camino de Formación"
    url = "/curriculo/"
    parent = "curriculo"
    weight = 1

[[menu.main]]
    name = "Materiales"
    url = "/courses/"
    parent = "curriculo"
    weight = 2

[[menu.main]]
    name = "Centros de Capacitación"
    url = "/centros/"
    weight = 4

[[menu.main]]
    name = "ROOTS"
    url = "/ROOTS/"
    weight = 5

[[menu.main]]
    name = "Participa"
    identifier = "participa"
    url = "/contacto/"
    weight = 6

[[menu.main]]
    name = "Implementar un Centro"
    url = "/contacto/"
    parent = "participa"
    weight = 1

[[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    parent = "participa"
    weight = 2

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel: +591 (6) 4908144"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
     weight = 2
    name = "Radio"
    url = "https://link.radioking.com/cgv"
    pre = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='M494.8 47c12.7-3.7 20-17.1 16.3-29.8S494-2.8 481.2 1L51.7 126.9c-9.4 2.7-17.9 7.3-25.1 13.2C10.5 151.7 0 170.6 0 192l0 4L0 304 0 448c0 35.3 28.7 64 64 64l384 0c35.3 0 64-28.7 64-64l0-256c0-35.3-28.7-64-64-64l-229.5 0L494.8 47z'/></svg>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:info@discipuladocgv.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    custom_css = ["css/custom_style.css"]

about_us = """
<p>
<strong>Cultivados en Gracia y Verdad</strong> existe para proveer currículo bíblico
y materiales diseñados para crear hacedores de discípulos mediante Centros de
Capacitación dirigidos por la iglesia, en la iglesia y para la iglesia.
</p>
"""

    disabled_logo = false
    logo_text = "CGV"

    logo = "img/cgv-logo.jpg"
    logo_small = "img/cgv-logo-small.jpg"
    contact_url = "/contacto"

UglifyURLs = true
CanonifyURLs = true
